FC:
- 3
- 3
LSTM:
- 7
- 7
- 7
SEED: 1
batch: 128
data_options:
  CGM: 3
  CHO: 0
  Insulin: 0
dropout: 0.3
epoch: 2000
input_size: 3
learning_rate: 0.0001
num_layers:
- 2
- 2
- 2
output_window: 6
stride: 1
